name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            .github/assets/snake.svg
            .github/assets/snake-dark.svg?palette=github-dark

      - name: Force commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 无条件强制覆盖文件
          git add .github/assets/ --force
          git commit -m "force: update snake heatmap [skip ci]" || true
          git push origin HEAD:main --force
